### ISSUE TITLE
RuntimeError: Factor is exactly singular

### ISSUE THREAD

**Issue by schorlton** [ZhangZhenmiao/METAMVGL#11]
Another one...thanks for your help!

```
  ERROR:root:stdout: initial binned contigs: 179
  binned contigs after remove ambiguous: 128
  non isolated contigs: 118
  non isolated binned contigs: 40
  Iteration 0  Alpla0 0.1257800736041923  Alpla1 4503599627370496.0  Obj_value 3.975192458333359
  Iteration 1  Alpla0 0.1277327488309996  Alpla1 2251799813685248.0  Obj_value 3.9144229226722356
  
  ERROR:root:stderr: Traceback (most recent call last):
    File "/usr/local/bin/METAMVGL.py", line 224, in <module>
      F_u = sp.sparse.linalg.inv(sp.sparse.eye(all_trans_uu.shape[0], format='csc', dtype=np.float64) - all_trans_uu).dot(all_trans_ul).dot(F_l)
    File "/opt/conda/envs/test/lib/python3.10/site-packages/scipy/sparse/linalg/_matfuncs.py", line 75, in inv
      Ainv = spsolve(A, I)
    File "/opt/conda/envs/test/lib/python3.10/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 282, in spsolve
      Afactsolve = factorized(A)
    File "/opt/conda/envs/test/lib/python3.10/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 574, in factorized
      return splu(A).solve
    File "/opt/conda/envs/test/lib/python3.10/site-packages/scipy/sparse/linalg/_dsolve/linsolve.py", line 413, in splu
      return _superlu.gstrf(N, A.nnz, A.data, A.indices, A.indptr,
  RuntimeError: Factor is exactly singular
```

**Comment by ZhangZhenmiao** [comment]
Thank you! I suspect this is an error related to machine accuracy, according to https://stackoverflow.com/questions/45683526/python-scipy-sparse-runtimeerror-factor-is-exactly-singular. I've submitted an update suppressing this bug.

**Comment by schorlton** [comment]
Thanks for be so responsive! Will give this a go. Closing with the assumption that it's fixed.
