### ISSUE TITLE
TypeError: float() argument must be a string or a real number, not 'csc_matrix'

### ISSUE THREAD

**Issue by schorlton** [ZhangZhenmiao/METAMVGL#12]
Thanks as always for your responsiveness and great tool. Hitting a new class of error when running on https://github.com/ZhangZhenmiao/METAMVGL/commit/92b7615b16b162c73e9f3e64930432516c0c9c00 and wondering if you have any ideas:

```bash
prep_graph --assembler=MEGAHIT -c final.contigs.fa -g megahit.fastg -b alignment.bam -o metamvgl_out --insert-size 605 --mapping-quality 2

Start loading fastg ...
Loaded 22 nodes, 2 links.
Done.
Start parsing alignments ...
Parsed 133337 lines ...
Done.
Start constructing PE overlap ...
Constructed PE overlap of 18 paths, new overlaps 8 ...
Done.
Start traversing assembly graph ...
Traversed edge neighbours of 22 paths ...
Done.
Start traversing PE graph ...
Traversed PE neighbours of 22 paths ...
Done.


METAMVGL.py --contigs final.contigs.fa --assembler MEGAHIT --assembly_graph metamvgl_out.ag --PE_graph metamvgl_out.pe --binned temp.csv --output temp_output

initial binned contigs: 1
binned contigs after remove ambiguous: 1
non isolated contigs: 2
non isolated binned contigs: 1

TypeError: float() argument must be a string or a real number, not 'csc_matrix'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/METAMVGL.py", line 230, in <module>
    F = sp.sparse.vstack([F_l, F_u], format='csc', dtype=np.float64)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/scipy/sparse/_construct.py", line 569, in vstack
    return bmat([[b] for b in blocks], format=format, dtype=dtype)
  File "/opt/conda/envs/test/lib/python3.10/site-packages/scipy/sparse/_construct.py", line 699, in bmat
    data[idx] = B.data
ValueError: setting an array element with a sequence.
```

**Comment by ZhangZhenmiao** [comment]
Sorry for the late reply. I am not sure about the error. Can you provide the input files final.contigs.fa, metamvgl_out.ag, metamvgl_out.pe and temp.csv to replicate the error? I will check it.

**Comment by schorlton** [comment]
No prob! Thanks for getting back to me. Just sent you an email with files to reproduce to the address associate with your GitHub account. Let me know if you need anything else.

**Comment by ZhangZhenmiao** [comment]
Hi Sam,

Sorry for the late! I am busy these days, but I found your issue has already been solved after Josh's [modification](https://github.com/ZhangZhenmiao/METAMVGL/pull/14). It runs smoothly on the files you provided. I appreciate your patience.

Best
Zhenmiao
