### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'jgi_summarize_bam_contig_depths'

### ISSUE THREAD

**Issue by kalonji08** [ZhangZhenmiao/METAMVGL#6]
Hello I'm getting the following Error:

[2022-08-23 22:23:05.060451] Metabat2_bam_depth starts: jgi_summarize_bam_contig_depths --outputDepth /home/kalonjilab2/MalebogoMScData/M1/MetaSpadesStrictM1/METAGVL_out2/MetaBat2/align.megahit.depth /home/kalonjilab2/MalebogoMScData/M1/MetaSpadesStrictM1/METAGVL_out2/MetaBat2/align.megahit.bam
Traceback (most recent call last):
  File "run_METAMVGL.py", line 209, in <module>
    run_cmd(
  File "run_METAMVGL.py", line 16, in run_cmd
    ret = subprocess.run(command, stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jgi_summarize_bam_contig_depths'

#This is the code i run:
python3 run_METAMVGL.py -a metaspades -r1 /home/kalonjilab2/MalebogoMScData/M1/raw_data/M1_R_1.fastq -r2 /home/kalonjilab2/MalebogoMScData/M1/raw_data/M1_R_2.fastq -c /home/kalonjilab2/MalebogoMScData/M1/MetaSpadesStrictM1/ASSEMBLY_200M1/metaspades/contigs.fasta -p /home/kalonjilab2/MalebogoMScData/M1/MetaSpadesStrictM1/ASSEMBLY_200M1/metaspades/contigs.paths -g /home/kalonjilab2/MalebogoMScData/M1/MetaSpadesStrictM1/ASSEMBLY_200M1/metaspades/assembly_graph.fastg -o /home/kalonjilab2/MalebogoMScData/M1/MetaSpadesStrictM1/METAGVL_out -t 18

Thanks for the assistance

**Comment by ZhangZhenmiao** [comment]
Thanks for using METAMVGL.

 "jgi_summarize_bam_contig_depths" is a component of MetaBAT2, which is required for "run_METAMVGL.py". MetaBAT2 could be installed from https://bitbucket.org/berkeleylab/metabat/src/master/, or bioconda https://anaconda.org/bioconda/metabat2.
