### ISSUE TITLE
networkx.exception.NetworkXError: nodelist has no nodes

### ISSUE THREAD

**Issue by schorlton** [ZhangZhenmiao/METAMVGL#8]
Thanks for creating METAMVGL! Hitting this bug and not sure what's going on. I suspect lack of overlap between graphs or a sparse graph with minimal to no connections:

```bash
prep_graph --assembler=MEGAHIT -c final.contigs.fa -g megahit.fastg -b alignment.bam -o metamvgl_out --insert-size 314 --mapping-quality 2
--
Start loading fastg ...
Loaded 1665 nodes, 76 links.
Done.
Start parsing alignments ...
Parsed 24235 lines ...
Done.
Start constructing PE overlap ...
Constructed PE overlap of 80 paths, new overlaps 32 ...
Done.
Start traversing assembly graph ...
Traversed edge neighbours of 1665 paths ...
Done.
Start traversing PE graph ...
Traversed PE neighbours of 1665 paths ...
Done.
 

METAMVGL.py --contigs final.contigs.fa --assembler MEGAHIT --assembly_graph metamvgl_out.ag --PE_graph metamvgl_out.pe --binned temp.csv --output temp_output

process exited with code: 1
Traceback (most recent call last):
File "/test/lib/python/nextflow.py", line 72, in run_cmd
result.check_returncode()
File "/opt/conda/envs/test/lib/python3.10/subprocess.py", line 457, in check_returncode
raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['METAMVGL.py', '--contigs', 'final.contigs.fa', '--assembler', 'MEGAHIT', '--assembly_graph', 'metamvgl_out.ag', '--PE_graph', 'metamvgl_out.pe', '--binned', 'temp.csv', '--output', 'temp_output']' returned non-zero exit status 1.

initial binned contigs: 10
binned contigs after remove ambiguous: 10
non isolated contigs: 0
non isolated binned contigs: 0
 
Traceback (most recent call last):
File "/usr/local/bin/METAMVGL.py", line 178, in <module>
assembly_graph_adjacent = nx.adjacency_matrix(assembly_graph, nodelist=non_isolated)
File "/opt/conda/envs/test/lib/python3.10/site-packages/networkx/linalg/graphmatrix.py", line 157, in adjacency_matrix
return nx.to_scipy_sparse_array(G, nodelist=nodelist, dtype=dtype, weight=weight)
File "/opt/conda/envs/test/lib/python3.10/site-packages/networkx/convert_matrix.py", line 558, in to_scipy_sparse_array
raise nx.NetworkXError("nodelist has no nodes")
networkx.exception.NetworkXError: nodelist has no nodes
```

**Comment by ZhangZhenmiao** [comment]
Thank you for using METAMVGL! From the log "non isolated contigs: 0", it means no edges are between the 10 binned contigs. I think this causes the crash. How many bins are there in MetaBat2/bin_ids.csv of the output folder?

**Comment by schorlton** [comment]
There are 3 bins as input, and the majority of contigs are unbinned. Should METAMVGL not handle the case of no edges between binned contigs?

**Comment by ZhangZhenmiao** [comment]
If there are no edges, the algorithm of METAMVGL wouldn't work. We can change the code to avoid the crash, but the binning result will have no difference from the initial binning.

**Comment by schorlton** [comment]
Thanks! I do think a more informative message would be helpful but now that I know this isn't bad I can catch the error and ignore. Closing issue.
