### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by schorlton** [ZhangZhenmiao/METAMVGL#9]
Thanks for creating METAMVGL! Hitting this bug and not sure what's going on. I suspect lack of overlap between graphs or a sparse graph with minimal to no connections:

```bash
prep_graph --assembler=MEGAHIT -c final.contigs.fa -g megahit.fastg -b alignment.bam -o metamvgl_out --insert-size 303 --mapping-quality 2
--
Start loading fastg ...
Loaded 6905 nodes, 30 links.
Done.
Start parsing alignments ...
Parsed 82540 lines ...
Done.
Start constructing PE overlap ...
Constructed PE overlap of 524 paths, new overlaps 106 ...
Done.
Start traversing assembly graph ...
Traversed edge neighbours of 6905 paths ...
Done.
Start traversing PE graph ...
Traversed PE neighbours of 6905 paths ...
Done.
 

METAMVGL.py --contigs final.contigs.fa --assembler MEGAHIT --assembly_graph metamvgl_out.ag --PE_graph metamvgl_out.pe --binned temp.csv --output temp_output

process exited with code: 1
Traceback (most recent call last):
File "/test/lib/python/nextflow.py", line 72, in run_cmd
result.check_returncode()
File "/opt/conda/envs/test/lib/python3.10/subprocess.py", line 457, in check_returncode
raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['METAMVGL.py', '--contigs', 'final.contigs.fa', '--assembler', 'MEGAHIT', '--assembly_graph', 'metamvgl_out.ag', '--PE_graph', 'metamvgl_out.pe', '--binned', 'temp.csv', '--output', 'temp_output']' returned non-zero exit status 1.
initial binned contigs: 683
binned contigs after remove ambiguous: 683
non isolated contigs: 12
non isolated binned contigs: 7
 
Traceback (most recent call last):
File "/usr/local/bin/METAMVGL.py", line 209, in <module>
alpha[1] = 0.5/obj2
ZeroDivisionError: float division by zero
```

**Comment by ZhangZhenmiao** [comment]
The error occurred when updating the weights of the PE graph and assembly graph. I think the input data is weird which makes the "obj2" zero value. Is it possible to provide your input file to METAMVGL? I can help check.

**Comment by schorlton** [comment]
Sent you an email to the email associated with your Github with some data to reproduce. Thanks again for your help!

**Comment by ZhangZhenmiao** [comment]
Thank you for providing the files to reproduce the error! The PE graph was very sparse which made the updating of the weight of the PE graph fail. I don't know why the graphs are so sparse -- I haven't seen this situation before. I have included some checks in the METAMVGL.py and it can continue running for this issue.

Thanks,
Zhenmiao

**Comment by schorlton** [comment]
Amazing - it works - thank you!
